### ISSUE TITLE
对于recycleview该如何用呢，

### ISSUE THREAD

**Issue by xie3120** [LeiHolmes/RxBindingDemo#1]
希望你能讲解下

**Comment by LeiHolmes** [comment]
抱歉才看到，关于RecyclerView我写过一篇文章，需要的话可以看一下：http://xulei.tech/2017/03/28/Material%20Design%E4%B9%8BRecyclerView%E5%9F%BA%E6%9C%AC%E8%AE%B2%E8%A7%A3%E4%B8%8E%E7%80%91%E5%B8%83%E6%B5%81%E7%9A%84%E5%AE%9E%E7%8E%B0/

**Comment by xie3120** [comment]
我不是说RecyclerView改如何使用，是rxbinding对RecyclerView的item的点击应该怎么处理

**Comment by LeiHolmes** [comment]
哦，我理解错了，RxBinding也有对RecyclerView支持，但是只提供了滚动状态的回调，所以我没写到Demo里了，如何实现Item点击目前还没有研究过，抱歉。
